### ISSUE TITLE
Broken links in Team page

### ISSUE THREAD

**Issue by Squadrick** [Project-MANAS/projectmanas.in#2]
Most of the links under each person redirects to `projectmanas.in` especially for Facebook and Github. 

The desirable behaviour would be to redirect to the correct link, and if the person doesn't have that service, to remove the corresponding icon.

**Comment by trickarcher** [comment]
Fixed the Issue in the latest  commit. There was an issue with the keyword `empty`, after replacing it by `nil` the issue was resolved. Also, fixed the issue where the Facebook links were being redirected to GitHub.
Check out this [thread](https://github.com/Shopify/liquid/issues/223#issuecomment-376816247) for more information about the conflict.
